### ISSUE TITLE
feature request: use site's favicon by default

### ISSUE THREAD

**Issue by mazany** [Exarilo/Flow.Launcher.Plugin.LinkOpener#2]
It would make sense to, **by default, use URL site's** `favicon.ico`, **unless specified otherwise**.

_At the moment, I have to visit the site, fetch the favicon, save it locally and then specify it in the configuration._

**Comment by Exarilo** [comment]
Thank you for your suggestions on my project ! 🙂
This one requires only minor adjustments and should be available pretty soon.
